export const en = {
  nav: {
    home: "HOME",
    about: "ABOUT",
    services: "SERVICES",
    portfolio: "PORTFOLIO",
    contact: "CONTACT",
  },
  header: {
    brand: "NEXTBEAVER",
    tagline: "DIGITAL CRAFTSMANSHIP",
    cta: "REQUEST AUDIT",
    openMenu: "Open menu",
  },
  toggles: {
    theme: "Theme",
    language: "Language",
    light: "Light",
    dark: "Dark",
    en: "EN",
    th: "TH",
  },
  hero: {
    eyebrow: "Architecture for the Digital Age",
    titleTop: "BESPOKE",
    titleStroke: "WEB SOLUTIONS",
    titleBottom: "REDEFINED.",
    body:
      "From high-performance corporate websites to complex enterprise software. We engineer digital solutions that function as flawlessly as they feel.",
    primaryCta: "DISCOVER THE CRAFT",
    secondaryCta: "VIEW SHOWREEL",
    scroll: "SCROLL",
  },
  about: {
    eyebrow: "THE ATELIER PHILOSOPHY",
    title: "THE INTERSECTION OF",
    titleAccent: "ART AND CODE",
    body: [
      "In a digital landscape cluttered with templates, we choose to tailor. Every line of code is a stitch, every pixel a deliberate choice in the fabric of your brand's digital identity.",
      "Our approach is not merely functional; it is emotional. We build platforms that don't just host content but elevate it, creating environments where your enterprise commands the authority it deserves.",
    ],
    highlight: {
      label: "Years of\nExcellence",
      value: "10+",
    },
    pillars: [
      {
        title: "Strategy First",
        body: "We diagnose before we design, ensuring every pixel serves a business purpose.",
      },
      {
        title: "Pixel Precision",
        body: "Obsessive attention to detail in motion, typography, and interaction.",
      },
    ],
  },
  process: {
    title: "Our Process",
    subtitle: "",
    steps: [
      {
        number: "01",
        title: "THE VISION",
        body: "Unveiling latent potential through deep discovery.",
        icon: "visibility",
      },
      {
        number: "02",
        title: "ARCHITECTURE",
        body: "Constructing the unseen lattice of strategy.",
        icon: "architecture",
        offsetClass: "md:pt-16",
      },
      {
        number: "03",
        title: "ALCHEMY",
        body: "Transmuting abstract concepts into visual gold.",
        icon: "science",
      },
      {
        number: "04",
        title: "THE FORGE",
        body: "Tempering the digital steel with robust code.",
        icon: "terminal",
        offsetClass: "md:pt-12",
      },
      {
        number: "05",
        title: "THE APEX",
        body: "Ascension to the digital zenith.",
        icon: "rocket_launch",
        highlight: true,
      },
    ],
    cta: {
      title: "Ready to Ascend?",
      body: "Begin your journey to the digital apex today. Let us craft your legacy.",
      button: "Initiate Sequence",
    },
  },
  services: {
    eyebrow: "CURATED CAPABILITIES",
    title: "BESPOKE SERVICES FOR DEMANDING BRANDS",
    viewAll: "VIEW ALL SERVICES",
    explore: "EXPLORE →",
    pricing: {
      closeLabel: "Close pricing modal",
      plans: [
        {
          title: "The Foundation",
          description: "For emerging visionaries establishing their digital footprint.",
          price: "2,500",
          currency: "$",
          period: "/mo",
          cta: "Begin Journey",
          featureIcon: "check_circle",
          features: [
            "Custom Design System",
            "React Development",
            "SEO Fundamentals",
            "Standard Animation Suite",
            "CMS Integration",
          ],
        },
        {
          title: "The Sovereign",
          description: "The zenith of performance for industry leaders.",
          price: "5,000",
          currency: "$",
          period: "/mo",
          cta: "Claim Sovereignty",
          badge: "Most Popular",
          featured: true,
          icon: "crown",
          featureIcon: "verified",
          features: [
            "3D WebGL Interactions",
            "Headless CMS Architecture",
            "Advanced Analytics Dashboard",
            "Priority Concierge Support",
            "Volumetric Lighting Effects",
            "Multi-Region Deployment",
          ],
        },
        {
          title: "The Imperial",
          description: "Unbounded power for global domination.",
          price: "Custom",
          cta: "Contact for Empire",
          featureIcon: "diamond",
          features: [
            "Dedicated Engineering Squad",
            "AR/VR Immersive Integration",
            "24/7 Global Concierge",
            "Custom AI Implementation",
            "Global CDN Deployment",
            "Bespoke SLA",
          ],
        },
      ],
    },
    items: [
      {
        icon: "architecture",
        title: "Corporate Websites & Platforms",
        body:
          "High-performance websites and web applications tailored for companies and student final projects.",
        features: ["Corporate Identity", "Student Final Projects", "Responsive Web Apps"],
        modalPlans: [
          {
            title: "Corporate Identity",
            description: "Professional websites that build trust and authority.",
            price: "Start 15k",
            currency: "THB",
            period: "",
            cta: "Get Proposal",
            featureIcon: "check_circle",
            features: [
              "Custom UX/UI Design",
              "Mobile Responsive",
              "Fast Loading Speed",
              "Basic SEO Setup",
              "Admin CMS System",
            ],
          },
          {
            title: "Web Application",
            description: "Complex web apps for specific business needs or final projects.",
            price: "Start 30k",
            currency: "THB",
            period: "",
            cta: "Consult Now",
            badge: "Best Value",
            featured: true,
            icon: "crown",
            featureIcon: "verified",
            features: [
              "Custom Database Design",
              "User Authentication",
              "API Integration",
              "Real-time Features",
              "Scalable Architecture",
              "Student Project Consulting",
            ],
          },
          {
            title: "Enterprise Platform",
            description: "Large-scale platforms with high security and performance.",
            price: "Custom",
            cta: "Contact Us",
            featureIcon: "diamond",
            features: [
              "Microservices Architecture",
              "Advanced Security",
              "High Traffic Support",
              "SLA Support",
              "Dedicated Team",
              "Full DevOps",
            ],
          },
        ],
      },
      {
        icon: "terminal",
        title: "Custom Business Software",
        body:
          "Tailor-made software solutions: Accounting, Payroll, Stock Management, and Realtime Systems.",
        features: ["Accounting & Payroll", "Realtime Stock", "API Development"],
        modalPlans: [
          {
            title: "Operational Tools",
            description: "Essential tools like Payroll or Simple Inventory systems.",
            price: "Start 25k",
            currency: "THB",
            period: "",
            cta: "Optimize Now",
            featureIcon: "check_circle",
            features: [
              "Payroll Calculation",
              "Employee Management",
              "Basic Inventory",
              "Report Generation",
              "User Roles",
            ],
          },
          {
            title: "Business Suite",
            description: "Comprehensive Accounting and Realtime Stock systems.",
            price: "Start 50k",
            currency: "THB",
            period: "",
            cta: "Build Suite",
            badge: "Top Tier",
            featured: true,
            icon: "crown",
            featureIcon: "verified",
            features: [
              "Full Accounting Module",
              "Realtime Stock Sync",
              "Barcode/QR Support",
              "Dashboard Analytics",
              "Multi-Branch Support",
              "API Connections",
            ],
          },
          {
            title: "Custom ERP",
            description: "Full-scale ERP tailored exactly to your business flow.",
            price: "Custom",
            cta: "Engineer ERP",
            featureIcon: "diamond",
            features: [
              "End-to-End Integration",
              "Legacy System Bridge",
              "Custom Workflows",
              "Advanced Permissions",
              "Audit Logs",
              "On-Premise or Cloud",
            ],
          },
        ],
      },
      {
        icon: "diamond",
        title: "Brand Evolution",
        body:
          "Strategic consulting to align your digital footprint with your market positioning.",
        features: ["Digital Strategy", "Content Direction", "Analytics & Growth"],
        modalPlans: [
          {
            title: "Brand Signal",
            description: "Clarify your positioning and brand narrative foundation.",
            price: "2,200",
            currency: "$",
            period: "/mo",
            cta: "Begin Strategy",
            featureIcon: "check_circle",
            features: [
              "Positioning Workshop",
              "Tone & Voice",
              "Content Pillars",
              "Visual Direction",
              "Brand Audit",
            ],
          },
          {
            title: "Legacy System",
            description: "A full brand system aligned for growth and scale.",
            price: "4,500",
            currency: "$",
            period: "/mo",
            cta: "Build Legacy",
            badge: "Most Popular",
            featured: true,
            icon: "crown",
            featureIcon: "verified",
            features: [
              "Brand Narrative",
              "Identity System",
              "Content Playbooks",
              "Launch Campaign",
              "Growth Analytics",
              "Stakeholder Alignment",
            ],
          },
          {
            title: "Monolith",
            description: "Global brand orchestration for enterprise portfolios.",
            price: "Custom",
            cta: "Contact Us",
            featureIcon: "diamond",
            features: [
              "Global Brand System",
              "Cross-Market Rollout",
              "Governance Model",
              "Executive Workshops",
              "Comms Strategy",
              "Long-Term Advisory",
            ],
          },
        ],
      },
      {
        icon: "auto_awesome",
        title: "Automation & AI",
        body:
          "Automation layers and AI copilots that streamline operations without sacrificing quality.",
        features: ["Workflow Automation", "AI Integrations", "Process Optimization"],
        modalPlans: [
          {
            title: "Automation Sprint",
            description: "Quick wins that remove bottlenecks and save time.",
            price: "2,900",
            currency: "$",
            period: "/mo",
            cta: "Start Automating",
            featureIcon: "check_circle",
            features: [
              "Process Mapping",
              "No-Code Automations",
              "Data Cleanup",
              "Baseline Dashboards",
              "Team Enablement",
            ],
          },
          {
            title: "AI Copilot",
            description: "Secure copilots that enhance decision-making.",
            price: "5,400",
            currency: "$",
            period: "/mo",
            cta: "Deploy Copilot",
            badge: "Most Popular",
            featured: true,
            icon: "crown",
            featureIcon: "verified",
            features: [
              "Custom AI Copilots",
              "LLM Workflows",
              "Secure Integrations",
              "Human-in-the-Loop",
              "Performance Monitoring",
              "Knowledge Base",
            ],
          },
          {
            title: "Autonomous Ops",
            description: "End-to-end automation for enterprise operations.",
            price: "Custom",
            cta: "Design Pipeline",
            featureIcon: "diamond",
            features: [
              "Autonomous Agents",
              "RPA + AI Orchestration",
              "Compliance Gates",
              "24/7 Observability",
              "SLA Automation",
              "Change Management",
            ],
          },
        ],
      },
    ],
  },
  portfolio: {
    eyebrow: "THE COLLECTION",
    title: "RECENT MASTERPIECES",
    swap: {
      badge: "Built for premium digital estates",
      stat: "03",
      statSuffix: "+",
      statLabel: "Flagship platforms in the Nextbeaver vault",
      brand: "Nextbeaver",
    },
    items: [
      {
        title: "VANTAGE FINANCE",
        subtitle: "Fintech Platform · UI/UX Design",
        number: "01",
      },
      {
        title: "AURA RESORTS",
        subtitle: "Hospitality · Full Stack Dev",
        number: "02",
      },
      {
        title: "NEXUS SYSTEMS",
        subtitle: "SaaS · Product Design",
        number: "03",
      },
    ],
  },
  portfolioPage: {
    badge: "AVAILABLE FOR SELECT PROJECTS",
    titleTop: "Digital",
    titleAccent: "Grandeur.",
    body:
      "Designing the absolute pinnacle of luxury web experiences. Where aesthetic opulence meets flawless technical execution.",
    cta: "VIEW ALL PROJECTS",
    modal: {
      descriptionLabel: "Project Description",
      techLabel: "Tech Stack",
      liveLabel: "Live",
    },
    pagination: {
      showing: "Showing",
      to: "to",
      of: "of",
      results: "results",
      prev: "Previous page",
      next: "Next page",
    },
    projects: [
      {
        id: "velvet-vine",
        label: "Shopify Plus",
        name: "Velvet & Vine",
        cardDescription: "Bespoke e-commerce with immersive 3D viewing.",
        cta: "View Case Study",
        description: [
          "Velvet & Vine is a luxury retail platform designed for premium catalog storytelling.",
          "We built a cinematic browsing experience with immersive visuals and seamless checkout."
        ],
        tech: ["Shopify Plus", "React", "3D Commerce", "Stripe", "Contentful"],
        breadcrumbs: "Home | Case Studies",
        previewImage: "/portfolio/anchorize.png",
      },
      {
        id: "nexus-trading",
        label: "FinTech",
        name: "Nexus\nTrading",
        cta: "View Dashboard",
        description: [
          "Nexus Trading delivers real-time market dashboards for institutional portfolios.",
          "We focused on dense data clarity with responsive, glanceable analytics."
        ],
        tech: ["Next.js", "TypeScript", "D3.js", "Postgres", "Vercel"],
        breadcrumbs: "Home | Dashboard",
        previewImage: "/portfolio/anchorize.png",
      },
      // ... (rest of projects can remain, or be updated if user provided specific portfolio items, but generic 'Student Project' example might be good to add if desired, but user didn't explicitly ask for dummy portfolio items, just 'services' description)
    ],
  },
  quote: {
    body:
      "\"Atelier didn't just build a website; they constructed a digital legacy for our firm. The attention to detail is simply unparalleled in the industry.\"",
    name: "Alexander Thorne",
    role: "CEO, Thorne Capital",
  },
  social: {
    share: "Share",
    phone: "Phone",
    facebook: "Facebook",
    line: "Line",
    instagram: "Instagram",
    mail: "Email",
  },
  contact: {
    eyebrow: "BEGIN THE DIALOGUE",
    titleTop: "READY TO ELEVATE",
    titleBottom: "YOUR PRESENCE?",
    body: "We take on a limited number of clients...",
    emailLabel: "Email Us",
    email: "hello@example.com",
    locationLabel: "Visit Us",
    location: "Zurich, Switzerland",
    form: {
      name: "Name",
      namePlaceholder: "John Doe",
      company: "Company",
      companyPlaceholder: "Acme Inc.",
      email: "Email",
      emailPlaceholder: "john@example.com",
      details: "Project Details",
      detailsPlaceholder: "Tell us about your goals...",
      submit: "Send Inquiry",
    }
  },
  seo: {
    title: "Nextbeaver Studio | Custom Websites, Web Apps & Business Software",
    description: "Expert web development for companies and student projects. We build Accounting Software, Payroll Systems, Realtime Stock Management, and Custom APIs.",
    keywords: "Web Development, Company Website, Student Project, Web Application, Accounting Software, Payroll System, Realtime Stock, API Development, Next.js Agency",
  },
  footer: {
    brand: "NEXTBEAVER",
    copyright: "© 2024 Nextbeaver Studio. All rights reserved.",
    rights: "All rights reserved.",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    links: ["Privacy Policy", "Terms of Service", "Contact"],
    social: "Social",
    contact: "Contact",
    address: "Bangkok, Thailand",
  },
};