export const th = {
  nav: {
    home: "หน้าหลัก",
    about: "เกี่ยวกับเรา",
    services: "บริการ",
    portfolio: "ผลงาน",
    contact: "ติดต่อเรา",
  },
  header: {
    brand: "NEXTBEAVER",
    tagline: "ดิจิทัลคราฟต์แมนชิพ",
    cta: "ขอคำปรึกษา",
    openMenu: "เปิดเมนู",
  },
  toggles: {
    theme: "ธีม",
    language: "ภาษา",
    light: "สว่าง",
    dark: "มืด",
    en: "EN",
    th: "TH",
  },
  hero: {
    eyebrow: "สถาปัตยกรรมแห่งยุคดิจิทัล",
    titleTop: "สร้างสรรค์",
    titleStroke: "เว็บโซลูชัน",
    titleBottom: "ไร้ขีดจำกัด",
    body:
      "ตั้งแต่เว็บไซต์องค์กรประสิทธิภาพสูง ไปจนถึงซอฟต์แวร์ทางธุรกิจที่ซับซ้อน เราวิศวกรรมโซลูชันดิจิทัลที่ทำงานได้อย่างไร้ที่ติพอๆ กับความรู้สึกที่ได้รับ",
    primaryCta: "ค้นพบผลงาน",
    secondaryCta: "ดูวิดีโอแนะนำ",
    scroll: "เลื่อนลง",
  },
  about: {
    eyebrow: "ปรัชญาของสตูดิโอ",
    title: "จุดบรรจบระหว่าง",
    titleAccent: "ศิลปะและโค้ด",
    body: [
      "ในโลกดิจิทัลที่เต็มไปด้วยเทมเพลตสำเร็จรูป เราเลือกที่จะตัดเย็บใหม่ ทุกบรรทัดของโค้ดคือการถักทอ ทุกพิกเซลคือการตัดสินใจอย่างประณีตในโครงสร้างอัตลักษณ์ดิจิทัลของแบรนด์คุณ",
      "แนวทางของเราไม่ได้แค่เน้นการใช้งาน แต่เน้นที่อารมณ์ความรู้สึก เราสร้างแพลตฟอร์มที่ไม่ใช่แค่ที่วางคอนเทนต์ แต่ช่วยยกระดับมัน สร้างพื้นที่ที่องค์กรของคุณจะได้รับความเชื่อถืออย่างที่ควรได้รับ",
    ],
    highlight: {
      label: "ปีแห่ง\nความเป็นเลิศ",
      value: "10+",
    },
    pillars: [
      {
        title: "กลยุทธ์ต้องมาก่อน",
        body: "เราวิเคราะห์ก่อนออกแบบ เพื่อให้มั่นใจว่าทุกพิกเซลตอบโจทย์ทางธุรกิจ",
      },
      {
        title: "ความแม่นยำระดับพิกเซล",
        body: "ใส่ใจในรายละเอียดอย่างบ้าคลั่ง ทั้งในเรื่องการเคลื่อนไหว ตัวอักษร และการโต้ตอบ",
      },
    ],
  },
  process: {
    title: "กระบวนการทำงาน",
    subtitle: "",
    steps: [
      {
        number: "01",
        title: "วิสัยทัศน์",
        body: "ค้นหาศักยภาพที่ซ่อนอยู่ผ่านการสำรวจอย่างลึกซึ้ง",
        icon: "visibility",
      },
      {
        number: "02",
        title: "สถาปัตยกรรม",
        body: "วางโครงสร้างกลยุทธ์ที่มองไม่เห็นให้แข็งแกร่ง",
        icon: "architecture",
        offsetClass: "md:pt-16",
      },
      {
        number: "03",
        title: "การแปรธาตุ",
        body: "เปลี่ยนแนวคิดนามธรรมให้กลายเป็นทองคำทางสายตา",
        icon: "science",
      },
      {
        number: "04",
        title: "การหลอมรวม",
        body: "ชุบแข็งดิจิทัลด้วยโค้ดที่ทรงพลังและเสถียร",
        icon: "terminal",
        offsetClass: "md:pt-12",
      },
      {
        number: "05",
        title: "จุดสูงสุด",
        body: "ทะยานสู่จุดสูงสุดแห่งโลกดิจิทัล",
        icon: "rocket_launch",
        highlight: true,
      },
    ],
    cta: {
      title: "พร้อมทะยานหรือยัง?",
      body: "เริ่มการเดินทางสู่จุดสูงสุดดิจิทัลของคุณวันนี้ ให้เราสร้างตำนานให้คุณ",
      button: "เริ่มโปรเจกต์",
    },
  },
  services: {
    eyebrow: "บริการที่ครอบคลุม",
    title: "โซลูชันเฉพาะทางสำหรับทุกความต้องการ",
    viewAll: "ดูบริการทั้งหมด",
    explore: "สำรวจ →",
    pricing: {
      closeLabel: "ปิดหน้าต่างราคา",
      plans: [
        {
          title: "The Foundation",
          description: "สำหรับผู้มีวิสัยทัศน์ใหม่ที่ต้องการสร้างตัวตนบนโลกดิจิทัล",
          price: "2,500",
          currency: "$",
          period: "/เดือน",
          cta: "เริ่มต้นการเดินทาง",
          featureIcon: "check_circle",
          features: [
            "ระบบดีไซน์เฉพาะตัว",
            "พัฒนาด้วย React",
            "พื้นฐาน SEO",
            "ชุด Animation มาตรฐาน",
            "เชื่อมต่อ CMS",
          ],
        },
        {
          title: "The Sovereign",
          description: "จุดสูงสุดของประสิทธิภาพสำหรับผู้นำอุตสาหกรรม",
          price: "5,000",
          currency: "$",
          period: "/เดือน",
          cta: "ครอบครองความเป็นเลิศ",
          badge: "ยอดนิยม",
          featured: true,
          icon: "crown",
          featureIcon: "verified",
          features: [
            "การโต้ตอบ 3D WebGL",
            "สถาปัตยกรรม Headless CMS",
            "แดชบอร์ดวิเคราะห์ขั้นสูง",
            "การดูแลระดับ Priority",
            "เอฟเฟกต์แสง Volumetric",
            "การวางระบบ Multi-Region",
          ],
        },
        {
          title: "The Imperial",
          description: "พลังไร้ขีดจำกัดสำหรับการครองตลาดระดับโลก",
          price: "ติดต่อสอบถาม",
          cta: "ติดต่อเพื่อสร้างอาณาจักร",
          featureIcon: "diamond",
          features: [
            "ทีมวิศวกรเฉพาะกิจ",
            "การผสาน AR/VR",
            "ผู้ดูแลส่วนตัว 24/7",
            "ระบบ AI เฉพาะองค์กร",
            "Global CDN Deployment",
            "SLA แบบกำหนดเอง",
          ],
        },
      ],
    },
    items: [
      {
        icon: "architecture",
        title: "รับทำเว็บไซต์ & แพลตฟอร์ม",
        body:
          "เว็บไซต์บริษัท โปรเจกต์จบนักศึกษา และเว็บแอปพลิเคชันที่รองรับทุกอุปกรณ์ ด้วยเทคโนโลยีทันสมัย",
        features: ["เว็บไซต์บริษัท", "โปรเจกต์จบนักศึกษา", "Responsive Web App"],
        modalPlans: [
          {
            title: "Corporate Identity",
            description: "เว็บไซต์บริษัทมืออาชีพ สร้างความน่าเชื่อถือให้องค์กร",
            price: "เริ่ม 15,000",
            currency: "บาท",
            period: "",
            cta: "ขอใบเสนอราคา",
            featureIcon: "check_circle",
            features: [
              "ดีไซน์ UX/UI เฉพาะตัว",
              "รองรับมือถือ (Mobile Responsive)",
              "โหลดเร็ว แรง",
              "ติดตั้งพื้นฐาน SEO",
              "ระบบจัดการเนื้อหา (CMS)",
            ],
          },
          {
            title: "Web Application",
            description: "เว็บแอปพลิเคชันซับซ้อน สำหรับธุรกิจหรือโปรเจกต์จบ",
            price: "เริ่ม 30,000",
            currency: "บาท",
            period: "",
            cta: "ปรึกษาเลย",
            badge: "คุ้มค่าที่สุด",
            featured: true,
            icon: "crown",
            featureIcon: "verified",
            features: [
              "ออกแบบ Database เฉพาะ",
              "ระบบสมาชิก Login",
              "เชื่อมต่อ API",
              "ฟีเจอร์ Real-time",
              "โครงสร้างรองรับการขยายตัว",
              "ที่ปรึกษาโปรเจกต์จบ",
            ],
          },
          {
            title: "Enterprise Platform",
            description: "แพลตฟอร์มขนาดใหญ่ ความปลอดภัยสูง รองรับคนใช้งานเยอะ",
            price: "ติดต่อสอบถาม",
            cta: "ติดต่อเรา",
            featureIcon: "diamond",
            features: [
              "สถาปัตยกรรม Microservices",
              "ความปลอดภัยขั้นสูง",
              "รองรับ High Traffic",
              "รับประกัน SLA",
              "ทีมงานดูแลส่วนตัว",
              "ระบบ DevOps เต็มรูปแบบ",
            ],
          },
        ],
      },
      {
        icon: "terminal",
        title: "รับเขียนโปรแกรมธุรกิจ",
        body:
          "โปรแกรมเฉพาะทาง: ระบบบัญชี, ระบบเงินเดือน, สต็อกสินค้า Realtime และการเชื่อมต่อ API",
        features: ["โปรแกรมบัญชี & เงินเดือน", "สต็อกสินค้า Realtime", "พัฒนา API"],
        modalPlans: [
          {
            title: "Operational Tools",
            description: "เครื่องมือจัดการพื้นฐาน เช่น ระบบเงินเดือน หรือ สต็อกอย่างง่าย",
            price: "เริ่ม 25,000",
            currency: "บาท",
            period: "",
            cta: "เพิ่มประสิทธิภาพ",
            featureIcon: "check_circle",
            features: [
              "คำนวณเงินเดือน",
              "จัดการข้อมูลพนักงาน",
              "ระบบสต็อกพื้นฐาน",
              "ออกรายงาน",
              "กำหนดสิทธิ์ผู้ใช้งาน",
            ],
          },
          {
            title: "Business Suite",
            description: "ชุดโปรแกรมครบวงจร บัญชี และ สต็อก Realtime",
            price: "เริ่ม 50,000",
            currency: "บาท",
            period: "",
            cta: "สร้างระบบ",
            badge: "ระดับโปร",
            featured: true,
            icon: "crown",
            featureIcon: "verified",
            features: [
              "โมดูลบัญชีครบวงจร",
              "ตัดสต็อก Realtime",
              "รองรับ Barcode/QR",
              "Dashboard วิเคราะห์ยอด",
              "รองรับหลายสาขา",
              "เชื่อมต่อ API ภายนอก",
            ],
          },
          {
            title: "Custom ERP",
            description: "ระบบ ERP เต็มรูปแบบ ออกแบบตาม Flow ธุรกิจของคุณเป๊ะๆ",
            price: "ติดต่อสอบถาม",
            cta: "ออกแบบ ERP",
            featureIcon: "diamond",
            features: [
              "เชื่อมโยงข้อมูลทั้งองค์กร",
              "เชื่อมต่อระบบเก่า (Legacy)",
              "Workflow เฉพาะตัว",
              "Permission ซับซ้อน",
              "ระบบ Audit Logs",
              "On-Premise หรือ Cloud",
            ],
          },
        ],
      },
      {
        icon: "diamond",
        title: "วิวัฒนาการแบรนด์",
        body:
          "ที่ปรึกษาเชิงกลยุทธ์เพื่อปรับรอยเท้าดิจิทัลของคุณให้ตรงกับตำแหน่งทางการตลาด",
        features: ["กลยุทธ์ดิจิทัล", "กำกับคอนเทนต์", "วิเคราะห์และการเติบโต"],
        modalPlans: [
          {
            title: "Brand Signal",
            description: "ระบุตำแหน่งและรากฐานการเล่าเรื่องของแบรนด์",
            price: "2,200",
            currency: "$",
            period: "/เดือน",
            cta: "เริ่มกลยุทธ์",
            featureIcon: "check_circle",
            features: [
              "เวิร์กช็อป Positioning",
              "โทนและเสียง",
              "เสาหลักคอนเทนต์",
              "ทิศทางภาพ",
              "ตรวจสอบแบรนด์",
            ],
          },
          {
            title: "Legacy System",
            description: "ระบบแบรนด์เต็มรูปแบบที่พร้อมสำหรับการเติบโตและขยายตัว",
            price: "4,500",
            currency: "$",
            period: "/เดือน",
            cta: "สร้างตำนาน",
            badge: "ยอดนิยม",
            featured: true,
            icon: "crown",
            featureIcon: "verified",
            features: [
              "เรื่องราวแบรนด์",
              "ระบบอัตลักษณ์",
              "คู่มือคอนเทนต์",
              "แคมเปญเปิดตัว",
              "วิเคราะห์การเติบโต",
              "การปรับจูนผู้มีส่วนได้ส่วนเสีย",
            ],
          },
          {
            title: "Monolith",
            description: "การจัดการแบรนด์ระดับโลกสำหรับพอร์ตโฟลิโอระดับองค์กร",
            price: "ติดต่อสอบถาม",
            cta: "ติดต่อเรา",
            featureIcon: "diamond",
            features: [
              "ระบบแบรนด์ระดับโลก",
              "ขยายสู่ตลาดข้ามชาติ",
              "โมเดลการกำกับดูแล",
              "เวิร์กช็อปผู้บริหาร",
              "กลยุทธ์การสื่อสาร",
              "ที่ปรึกษาระยะยาว",
            ],
          },
        ],
      },
      {
        icon: "auto_awesome",
        title: "ระบบอัตโนมัติ & AI",
        body:
          "เลเยอร์อัตโนมัติและผู้ช่วย AI ที่ช่วยลดขั้นตอนการทำงานโดยไม่ลดทอนคุณภาพ",
        features: ["Automate Workflow", "เชื่อมต่อ AI", "ปรับปรุงกระบวนการ"],
        modalPlans: [
          {
            title: "Automation Sprint",
            description: "ชัยชนะระยะสั้นที่ขจัดคอขวดและประหยัดเวลา",
            price: "2,900",
            currency: "$",
            period: "/เดือน",
            cta: "เริ่มอัตโนมัติ",
            featureIcon: "check_circle",
            features: [
              "แผนผังกระบวนการ",
              "No-Code Automations",
              "ทำความสะอาดข้อมูล",
              "แดชบอร์ดพื้นฐาน",
              "เตรียมความพร้อมทีม",
            ],
          },
          {
            title: "AI Copilot",
            description: "ผู้ช่วยที่ปลอดภัยเพื่อเสริมการตัดสินใจ",
            price: "5,400",
            currency: "$",
            period: "/เดือน",
            cta: "ติดตั้ง Copilot",
            badge: "ยอดนิยม",
            featured: true,
            icon: "crown",
            featureIcon: "verified",
            features: [
              "AI Copilots เฉพาะตัว",
              "Workflow LLM",
              "การเชื่อมต่อที่ปลอดภัย",
              "Human-in-the-Loop",
              "ตรวจสอบประสิทธิภาพ",
              "ฐานความรู้",
            ],
          },
          {
            title: "Autonomous Ops",
            description: "ระบบอัตโนมัติแบบ End-to-end สำหรับการดำเนินงานระดับองค์กร",
            price: "ติดต่อสอบถาม",
            cta: "ออกแบบ Pipeline",
            featureIcon: "diamond",
            features: [
              "Autonomous Agents",
              "RPA + AI Orchestration",
              "ประตู Compliance",
              "ตรวจสอบ 24/7",
              "SLA Automation",
              "การจัดการการเปลี่ยนแปลง",
            ],
          },
        ],
      },
    ],
  },
  portfolio: {
    eyebrow: "คอลเลกชัน",
    title: "ผลงานชิ้นเอกล่าสุด",
    swap: {
      badge: "สร้างเพื่ออสังหาริมทรัพย์ดิจิทัลระดับพรีเมียม",
      stat: "03",
      statSuffix: "+",
      statLabel: "แพลตฟอร์มเรือธงในคลัง Nextbeaver",
      brand: "Nextbeaver",
    },
    items: [
      {
        title: "VANTAGE FINANCE",
        subtitle: "แพลตฟอร์มฟินเทค · ออกแบบ UI/UX",
        number: "01",
      },
      {
        title: "AURA RESORTS",
        subtitle: "ธุรกิจบริการ · พัฒนา Full Stack",
        number: "02",
      },
      {
        title: "NEXUS SYSTEMS",
        subtitle: "SaaS · ออกแบบผลิตภัณฑ์",
        number: "03",
      },
    ],
  },
  portfolioPage: {
    badge: "เปิดรับโปรเจกต์คัดสรร",
    titleTop: "ความยิ่งใหญ่",
    titleAccent: "ทางดิจิทัล",
    body:
      "ออกแบบประสบการณ์เว็บหรูหราขั้นสูงสุด ที่ซึ่งความมั่งคั่งทางสุนทรียศาสตร์มาบรรจบกับการทำงานทางเทคนิคที่ไร้ที่ติ",
    cta: "ดูโปรเจกต์ทั้งหมด",
    modal: {
      descriptionLabel: "รายละเอียดโปรเจกต์",
      techLabel: "เทคโนโลยี",
      liveLabel: "ดูของจริง",
    },
    pagination: {
      showing: "แสดง",
      to: "ถึง",
      of: "จาก",
      results: "รายการ",
      prev: "หน้าก่อนหน้า",
      next: "หน้าถัดไป",
    },
    projects: [
      {
        id: "velvet-vine",
        label: "Shopify Plus",
        name: "Velvet & Vine",
        cardDescription: "อีคอมเมิร์ซสั่งตัดพร้อมมุมมอง 3D ที่น่าตื่นตา",
        cta: "ดูกรณีศึกษา",
        description: [
          "Velvet & Vine คือแพลตฟอร์มค้าปลีกหรูที่ออกแบบมาเพื่อการเล่าเรื่องแคตตาล็อกระดับพรีเมียม",
          "เราสร้างประสบการณ์การเลือกชมแบบภาพยนตร์ด้วยภาพที่น่าตื่นตาและการชำระเงินที่ลื่นไหล"
        ],
        tech: ["Shopify Plus", "React", "3D Commerce", "Stripe", "Contentful"],
        breadcrumbs: "หน้าหลัก | กรณีศึกษา",
        previewImage: "/portfolio/anchorize.png",
      },
      {
        id: "nexus-trading",
        label: "FinTech",
        name: "Nexus\nTrading",
        cta: "ดูแดชบอร์ด",
        description: [
          "Nexus Trading นำเสนอแดชบอร์ดตลาดแบบเรียลไทม์สำหรับพอร์ตการลงทุนสถาบัน",
          "เราเน้นความชัดเจนของข้อมูลที่หนาแน่นด้วยการวิเคราะห์ที่ตอบสนองและดูง่าย"
        ],
        tech: ["Next.js", "TypeScript", "D3.js", "Postgres", "Vercel"],
        breadcrumbs: "หน้าหลัก | แดชบอร์ด",
        previewImage: "/portfolio/anchorize.png",
      },
      {
        id: "archstudio",
        label: "WebGL",
        name: "ArchStudio",
        cta: "สำรวจ",
        description: [
          "ArchStudio แสดงผลงานสถาปัตยกรรมผ่านแกลเลอรีแบบโต้ตอบที่น่าตื่นตา",
          "เราสร้างประสบการณ์แกลเลอรีที่ยกระดับความลึก แสง และการเคลื่อนไหว"
        ],
        tech: ["WebGL", "Three.js", "GSAP", "Vite", "Figma"],
        breadcrumbs: "หน้าหลัก | โชว์เคส",
        previewImage: "/portfolio/anchorize.png",
      },
      {
        id: "aura-ai",
        label: "Next.js",
        name: "Aura AI",
        cta: "สำรวจ",
        description: [
          "Aura AI นำข้อมูลเชิงลึกมาสู่อินเทอร์เฟซผลิตภัณฑ์ที่สะอาดและน่าเชื่อถือ",
          "เราปรับปรุงลำดับชั้นและระยะห่างเพื่อให้ผลลัพธ์ที่ซับซ้อนอ่านง่าย"
        ],
        tech: ["Next.js", "TypeScript", "Tailwind", "Supabase", "Figma"],
        breadcrumbs: "หน้าหลัก | ผลิตภัณฑ์",
        previewImage: "/portfolio/anchorize.png",
      },
      {
        id: "healthsync",
        label: "App Dev",
        name: "HealthSync App",
        cta: "ดูแอป",
        description: [
          "HealthSync เชื่อมโยงข้อมูลผู้ป่วยระหว่างมือถือและแดชบอร์ดคลินิก",
          "เราปรับปรุงการเริ่มต้นใช้งานเพื่อความเร็วและลดเวลาฝึกอบรมพนักงาน"
        ],
        tech: ["React Native", "Node.js", "GraphQL", "Firebase", "Framer"],
        breadcrumbs: "หน้าหลัก | มือถือ",
        previewImage: "/portfolio/anchorize.png",
      },
      {
        id: "obsidian",
        label: "Branding",
        name: "Obsidian Identity",
        cta: "ดูอัตลักษณ์",
        description: [
          "Obsidian Identity กำหนดระบบหรูหราของตัวอักษร การเคลื่อนไหว และน้ำเสียง",
          "เราส่งมอบชุดแบรนด์ที่สอดคล้องกันทั่วทั้งสื่อสิ่งพิมพ์และดิจิทัล"
        ],
        tech: ["Brand System", "Typography", "Motion", "Illustration", "Guidelines"],
        breadcrumbs: "หน้าหลัก | แบรนด์",
        previewImage: "/portfolio/anchorize.png",
      },
      {
        id: "lumen-atelier",
        label: "Commerce",
        name: "Lumen Atelier",
        cta: "ดูหน้าร้าน",
        description: [
          "Lumen Atelier ยกระดับการเลือกชมแคตตาล็อกด้วยเลย์เอาต์แบบนิตยสาร",
          "เราปรับปรุงหน้าร้านเพื่อการแปลงยอดขายสูงโดยไม่ลดทอนความประณีต"
        ],
        tech: ["Next.js", "Shopify", "Tailwind", "Algolia", "Contentful"],
        breadcrumbs: "หน้าหลัก | การค้า",
        previewImage: "/portfolio/anchorize.png",
      },
      {
        id: "citadel-cloud",
        label: "Cloud Ops",
        name: "Citadel Cloud",
        cta: "ดูแพลตฟอร์ม",
        description: [
          "Citadel Cloud รวมโครงสร้างพื้นฐานหลายภูมิภาคด้วยแผงควบคุมเดียว",
          "เราออกแบบแดชบอร์ดที่ทำให้ระบบซับซ้อนดูสงบและอ่านง่าย"
        ],
        tech: ["React", "TypeScript", "Kubernetes", "Grafana", "Supabase"],
        breadcrumbs: "หน้าหลัก | แพลตฟอร์ม",
        previewImage: "/portfolio/anchorize.png",
      },
      {
        id: "aurora-bank",
        label: "FinTech",
        name: "Aurora Bank",
        cta: "ดูประสบการณ์",
        description: [
          "Aurora Bank นำเสนอชุดธนาคารดิจิทัลที่สง่างามสำหรับลูกค้าส่วนตัว",
          "เราเน้นที่ความไว้วางใจ ความปลอดภัย และการเริ่มต้นใช้งานที่ลื่นไหล"
        ],
        tech: ["Next.js", "TypeScript", "Vault", "Postgres", "Figma"],
        breadcrumbs: "หน้าหลัก | การเงิน",
        previewImage: "/portfolio/anchorize.png",
      },
      {
        id: "helios-hospitality",
        label: "Hospitality",
        name: "Helios Hospitality",
        cta: "ดูอสังหาริมทรัพย์",
        description: [
          "Helios Hospitality นำเสนอเรื่องราวอสังหาริมทรัพย์และการจองที่น่าตื่นตา",
          "เราสมดุลภาพที่หรูหรากับเลย์เอาต์ที่เน้นประสิทธิภาพ"
        ],
        tech: ["Next.js", "Storyblok", "GSAP", "Vercel", "GA4"],
        breadcrumbs: "หน้าหลัก | การต้อนรับ",
        previewImage: "/portfolio/anchorize.png",
      },
      {
        id: "northstar-analytics",
        label: "Analytics",
        name: "Northstar Analytics",
        cta: "ดูแดชบอร์ด",
        description: [
          "Northstar Analytics แสดงข้อมูลเชิงลึกพอร์ตโฟลิโอด้วยการพยากรณ์แบบพลวัต",
          "เราปรับจูนการแสดงภาพข้อมูลเพื่อภาพรวมที่เหมาะกับผู้บริหาร"
        ],
        tech: ["React", "D3.js", "Node.js", "Snowflake", "Figma"],
        breadcrumbs: "หน้าหลัก | การวิเคราะห์",
        previewImage: "/portfolio/anchorize.png",
      },
      {
        id: "echelon-labs",
        label: "Research",
        name: "Echelon Labs",
        cta: "ดูห้องแล็บ",
        description: [
          "Echelon Labs นำเสนอความก้าวหน้าทางวิทยาศาสตร์ด้วยเรื่องราวที่ขัดเกลา",
          "เราสร้างระบบเรื่องราวแบบโมดูลาร์สำหรับการเปิดตัวและสื่อ"
        ],
        tech: ["Next.js", "MDX", "Tailwind", "Framer", "Contentful"],
        breadcrumbs: "หน้าหลัก | วิจัย",
        previewImage: "/portfolio/anchorize.png",
      },
    ],
  },
  quote: {
    body:
      "\"Atelier ไม่ได้แค่สร้างเว็บไซต์; พวกเขาสร้างมรดกทางดิจิทัลให้กับบริษัทของเรา ความใส่ใจในรายละเอียดนั้นหาตัวจับยากในวงการ\"",
    name: "Alexander Thorne",
    role: "CEO, Thorne Capital",
  },
  social: {
    share: "แชร์",
    phone: "โทรศัพท์",
    facebook: "Facebook",
    line: "Line",
    instagram: "Instagram",
    mail: "อีเมล",
  },
  contact: {
    eyebrow: "เริ่มต้นการสนทนา",
    titleTop: "พร้อมที่จะยกระดับ",
    titleBottom: "ตัวตนของคุณหรือยัง?",
    body: "เรารับลูกค้าน้อยรายต่อปีเพื่อให้แน่ใจว่าจะได้รับความเอาใจใส่อย่างเต็มที่ บอกเราเกี่ยวกับวิสัยทัศน์ของคุณ",
    emailLabel: "อีเมลหาเรา",
    email: "hello@example.com",
    locationLabel: "เยี่ยมชมเรา",
    location: "กรุงเทพมหานคร, ประเทศไทย",
    form: {
      name: "ชื่อ",
      namePlaceholder: "ชื่อของคุณ",
      company: "บริษัท",
      companyPlaceholder: "ชื่อบริษัท (ถ้ามี)",
      email: "อีเมล",
      emailPlaceholder: "yourname@example.com",
      details: "รายละเอียดโปรเจกต์",
      detailsPlaceholder: "บอกเราเกี่ยวกับเป้าหมายของคุณ...",
      submit: "ส่งข้อมูลสอบถาม",
    }
  },
  seo: {
    title: "Nextbeaver Studio | รับทำเว็บไซต์ บริษัท โปรเจกต์จบ แอปพลิเคชัน & โปรแกรมบัญชี",
    description: "รับเขียนโปรแกรมครบวงจร เว็บไซต์บริษัท โปรเจกต์จบนักศึกษา เว็บแอปพลิเคชัน โปรแกรมบัญชี เงินเดือน สต็อกสินค้า Realtime และพัฒนา API โดยมืออาชีพ",
    keywords: "รับทำเว็บไซต์บริษัท, รับทำโปรเจกต์จบนักศึกษา, เว็บแอปพลิเคชัน, โปรแกรมบัญชี, โปรแกรมเงินเดือน, โปรแกรมสต็อกสินค้า, พัฒนา API, Next.js Agency",
  },
  footer: {
    brand: "NEXTBEAVER",
    copyright: "© 2024 Nextbeaver Studio. สงวนลิขสิทธิ์.",
    rights: "สงวนลิขสิทธิ์.",
    privacy: "นโยบายความเป็นส่วนตัว",
    terms: "เงื่อนไขการให้บริการ",
    links: ["นโยบายความเป็นส่วนตัว", "เงื่อนไขการให้บริการ", "ติดต่อ"],
    social: "โซเชียล",
    contact: "ติดต่อ",
    address: "กรุงเทพมหานคร, ประเทศไทย",
  },
};
