insert into process_content (title, title_th, subtitle, subtitle_th)
values (
  'Our Process',
  'Our Process',
  '',
  ''
);

insert into process_styles (
  title_color_light,
  title_color_dark,
  title_font_family_en,
  title_font_family_th,
  title_font_size,
  subtitle_color_light,
  subtitle_color_dark,
  subtitle_font_family_en,
  subtitle_font_family_th,
  subtitle_font_size,
  accent_color_light,
  accent_color_dark,
  step_icon_color_light,
  step_icon_color_dark,
  step_number_color_light,
  step_number_color_dark,
  step_title_color_light,
  step_title_color_dark,
  step_title_font_family_en,
  step_title_font_family_th,
  step_title_font_size,
  step_body_color_light,
  step_body_color_dark,
  step_body_font_family_en,
  step_body_font_family_th,
  step_body_font_size,
  line_base_color_light,
  line_base_color_dark,
  line_accent_color_light,
  line_accent_color_dark,
  line_dash_color_light,
  line_dash_color_dark,
  line_pulse_duration_desktop,
  line_pulse_duration_mobile,
  line_dash_duration_desktop,
  line_dash_duration_mobile
)
values (
  '#1b140f',
  '#ffffff',
  'Space Grotesk, sans-serif',
  'Space Grotesk, sans-serif',
  48,
  '#6b5d52',
  '#bbab9b',
  'Space Grotesk, sans-serif',
  'Space Grotesk, sans-serif',
  16,
  '#f97316',
  '#f98c1f',
  '#1b140f',
  '#ffffff',
  '#f97316',
  '#f98c1f',
  '#1b140f',
  '#ffffff',
  'Space Grotesk, sans-serif',
  'Space Grotesk, sans-serif',
  20,
  '#6b5d52',
  '#bbab9b',
  'Space Grotesk, sans-serif',
  'Space Grotesk, sans-serif',
  14,
  '#ffedd5',
  '#3a3027',
  '#f97316',
  '#f98c1f',
  '#ffffff',
  '#f98c1f',
  6,
  4,
  8,
  8
);

insert into process_steps (
  number,
  title,
  title_th,
  body,
  body_th,
  icon,
  icon_color_light,
  icon_color_dark,
  highlight,
  offset_class,
  title_color_light,
  title_color_dark,
  title_font_family_en,
  title_font_family_th,
  title_font_size,
  body_color_light,
  body_color_dark,
  body_font_family_en,
  body_font_family_th,
  body_font_size,
  order_index
)
values
  (
    '01',
    'THE VISION',
    'THE VISION',
    'Unveiling latent potential through deep discovery.',
    'Unveiling latent potential through deep discovery.',
    'visibility',
    '#1b140f',
    '#ffffff',
    false,
    null,
    '#1b140f',
    '#ffffff',
    'Space Grotesk, sans-serif',
    'Space Grotesk, sans-serif',
    20,
    '#6b5d52',
    '#bbab9b',
    'Space Grotesk, sans-serif',
    'Space Grotesk, sans-serif',
    14,
    0
  ),
  (
    '02',
    'ARCHITECTURE',
    'ARCHITECTURE',
    'Constructing the unseen lattice of strategy.',
    'Constructing the unseen lattice of strategy.',
    'architecture',
    '#1b140f',
    '#ffffff',
    false,
    'md:pt-16',
    '#1b140f',
    '#ffffff',
    'Space Grotesk, sans-serif',
    'Space Grotesk, sans-serif',
    20,
    '#6b5d52',
    '#bbab9b',
    'Space Grotesk, sans-serif',
    'Space Grotesk, sans-serif',
    14,
    1
  ),
  (
    '03',
    'ALCHEMY',
    'ALCHEMY',
    'Transmuting abstract concepts into visual gold.',
    'Transmuting abstract concepts into visual gold.',
    'science',
    '#1b140f',
    '#ffffff',
    false,
    null,
    '#1b140f',
    '#ffffff',
    'Space Grotesk, sans-serif',
    'Space Grotesk, sans-serif',
    20,
    '#6b5d52',
    '#bbab9b',
    'Space Grotesk, sans-serif',
    'Space Grotesk, sans-serif',
    14,
    2
  ),
  (
    '04',
    'THE FORGE',
    'THE FORGE',
    'Tempering the digital steel with robust code.',
    'Tempering the digital steel with robust code.',
    'terminal',
    '#1b140f',
    '#ffffff',
    false,
    'md:pt-12',
    '#1b140f',
    '#ffffff',
    'Space Grotesk, sans-serif',
    'Space Grotesk, sans-serif',
    20,
    '#6b5d52',
    '#bbab9b',
    'Space Grotesk, sans-serif',
    'Space Grotesk, sans-serif',
    14,
    3
  ),
  (
    '05',
    'THE APEX',
    'THE APEX',
    'Ascension to the digital zenith.',
    'Ascension to the digital zenith.',
    'rocket_launch',
    '#1b140f',
    '#ffffff',
    true,
    null,
    '#1b140f',
    '#ffffff',
    'Space Grotesk, sans-serif',
    'Space Grotesk, sans-serif',
    20,
    '#6b5d52',
    '#bbab9b',
    'Space Grotesk, sans-serif',
    'Space Grotesk, sans-serif',
    14,
    4
  );
